version: '3.8'


services:
  db:
    image: postgres:17
    container_name: sokoni_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sokoni
      POSTGRES_USER: sokoni
      POSTGRES_PASSWORD: sokoni
      TZ: Asia/Tokyo
    volumes:
      - sokoni_pgdata:/var/lib/postgresql/data

  sokoni:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://sokoni:sokoni@db:5432/sokoni?sslmode=disable
      - TZ=Asia/Tokyo
    command: ["scheduler"]

volumes:
  sokoni_pgdata:
